name: DevOps & Cloud Infrastructure CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  validate-and-build:
    runs-on: ubuntu-latest

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_DEFAULT_REGION: 'us-east-1'

    steps:
    - name: Checkout Code Repository
      uses: actions/checkout@v4

    - name: Initialize Python Runtime
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Run Syntax and Quality Linting (Flake8)
      run: |
        pip install flake8
        flake8 . --count --exclude=Core-Utilities,CSS-200T,Network-Infrastructure,Inventory-Automation --select=E9,F63,F7,F82 --show-source --statistics

    # 🔒 DEVSECOPS STEP: Explicitly skipping B311 and B310 to allow our safe public REST API configuration
    - name: Run Automated Security Scan (Bandit)
      run: |
        pip install bandit
        bandit -r ./Phase1-Container-Stream ./Phase2-Cloud-Serverless -s B311,B310

    - name: Setup Terraform CLI
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: "1.7.0"

    - name: Validate Terraform Infrastructure Plan
      run: |
        cd Phase2-Cloud-Serverless
        terraform init -upgrade
        terraform validate

    - name: Validate and Build Phase 1 Docker Image
      run: |
        cd Phase1-Container-Stream
        docker build -t inventory-stream-pipeline:latest .

